import { registerTool } from "./toolRegistry.js";
import { generateScriptTool } from "./generateScript.tool.js";
import { generateScriptStyleTool } from "./generateScriptStyle.tool.js";
import { generateVoiceTool } from "./generateVoice.tool.js";
import { listVoicesTool } from "./listVoices.tool.js";
import { previewVoiceTool } from "./previewVoice.tool.js";
import { transcribeAudioTool } from "./transcribeAudio.tool.js";
import { searchStockTool } from "./searchStock.tool.js";
import { generateStockKeywordsTool } from "./generateStockKeywords.tool.js";
import { generateVisualContextTool } from "./generateVisualContext.tool.js";
import { generateImageTool } from "./generateImage.tool.js";
import { generateVideoTool } from "./generateVideo.tool.js";
import { generateVideoPromptTool } from "./generateVideoPrompt.tool.js";
import { generateOverlayTool } from "./generateOverlay.tool.js";
import { renderVideoTool } from "./renderVideo.tool.js";
import { buildTimelineTool } from "./buildTimeline.tool.js";
import { buildScenesTool } from "./buildScenes.tool.js";

export { runTool, listTools, getTool } from "./toolRegistry.js";
export type { ToolContext, ToolDefinition } from "./tool.types.js";
export { ProviderNotConfiguredError } from "./tool.errors.js";

registerTool(generateScriptTool);
registerTool(generateScriptStyleTool);
registerTool(generateVoiceTool);
registerTool(listVoicesTool);
registerTool(previewVoiceTool);
registerTool(transcribeAudioTool);
registerTool(searchStockTool);
registerTool(generateStockKeywordsTool);
registerTool(generateVisualContextTool);
registerTool(generateImageTool);
registerTool(generateVideoTool);
registerTool(generateVideoPromptTool);
registerTool(generateOverlayTool);
registerTool(renderVideoTool);
registerTool(buildTimelineTool);
registerTool(buildScenesTool);
